import sqlite3
import back
#import sqlite3 import Error

#####################       BANCO DE DADOS (Separar em um novo .py)     ##########################
# Definindo os parametros do Banco de dados ## 
dbase = sqlite3.connect("projeto.db")
c = dbase.cursor()

dbase.commit()


### Criando o Banco de Dados ###
dbase.execute(''' CREATE TABLE IF NOT EXISTS tb_relatorio(
        T_PEP   VARCHAR(30) PRIMARY KEY NOT NULL,
        T_NOMEPROJETO VARCHAR(50),
        B_ok_11		BOOLEAN,
        B_no_11		BOOLEAN,
        B_na_11		BOOLEAN,
        B_ok_12		BOOLEAN,
        B_no_12		BOOLEAN,
        B_na_12		BOOLEAN,
        B_ok_13		BOOLEAN,
        B_no_13		BOOLEAN,
        B_na_13		BOOLEAN,
        B_ok_14		BOOLEAN,
        B_no_14		BOOLEAN,
        B_na_14		BOOLEAN,
        B_ok_15		BOOLEAN,
        B_no_15		BOOLEAN,
        B_na_15		BOOLEAN,
        B_ok_16		BOOLEAN,
        B_no_16		BOOLEAN,
        B_na_16		BOOLEAN,
        B_ok_17		BOOLEAN,
        B_no_17		BOOLEAN,
        B_na_17		BOOLEAN,
        B_ok_21		BOOLEAN, 
        B_no_21		BOOLEAN,
        B_na_21		BOOLEAN,
        B_ok_22		BOOLEAN, 
        B_no_22		BOOLEAN,
        B_na_22		BOOLEAN,
        B_ok_23		BOOLEAN, 
        B_no_23		BOOLEAN,
        B_na_23		BOOLEAN,
        B_ok_24		BOOLEAN, 
        B_no_24		BOOLEAN,
        B_na_24		BOOLEAN,
        B_ok_25		BOOLEAN,
        B_no_25		BOOLEAN,
        B_na_25		BOOLEAN,
        B_ok_26		BOOLEAN, 
        B_no_26		BOOLEAN,
        B_na_26		BOOLEAN,
        B_ok_27		BOOLEAN, 
        B_no_27		BOOLEAN,
        B_na_27 	BOOLEAN,
        B_ok_31		BOOLEAN,
        B_no_31		BOOLEAN,
        B_na_31		BOOLEAN,
        B_ok_32		BOOLEAN,
        B_no_32		BOOLEAN,
        B_na_32		BOOLEAN,
        B_ok_33		BOOLEAN,
        B_no_33		BOOLEAN,
        B_na_33		BOOLEAN,
        B_ok_34		BOOLEAN,
        B_no_34		BOOLEAN,
        B_na_34		BOOLEAN,
        B_ok_35		BOOLEAN,
        B_no_35		BOOLEAN,
        B_na_35		BOOLEAN,
        B_ok_36		BOOLEAN,
        B_no_36		BOOLEAN,
        B_na_36		BOOLEAN,
        T_INSTRUMENTO1		VARCHAR(20),
        T_INSTRUMENTO2		VARCHAR(20),
        T_INSTRUMENTO3		VARCHAR(20),
        T_INSTRUMENTO4		VARCHAR(20),
        T_INSTRUMENTO5		VARCHAR(20),
        T_INSTRUMENTO6		VARCHAR(20),
        T_INSTRUMENTO7		VARCHAR(20),
        T_INSTRUMENTO8		VARCHAR(20),
      	T_REGISTRO1				VARCHAR(20),
        T_REGISTRO2				VARCHAR(20),
        T_REGISTRO3				VARCHAR(20),
        T_REGISTRO4				VARCHAR(20),
        T_REGISTRO5				VARCHAR(20),
        T_REGISTRO6				VARCHAR(20),
        T_REGISTRO7				VARCHAR(20),
		    T_REGISTRO8				VARCHAR(20),
        T_VALIDADE1				VARCHAR(20),
        T_VALIDADE2				VARCHAR(20),
        T_VALIDADE3				VARCHAR(20),
        T_VALIDADE4				VARCHAR(20),
        T_VALIDADE5				VARCHAR(20),
        T_VALIDADE6				VARCHAR(20),
        T_VALIDADE7				VARCHAR(20),
        T_VALIDADE8				VARCHAR(20))''')

# Aplica as mudanças no banco de dados
dbase.commit()



# Função escreve os valores das variaveis #
def write():
    c.execute(""" INSERT into tb_relatorio(T_PEP,
        T_NOMEPROJETO,
        B_ok_11,
        B_no_11,
        B_na_11,
        B_ok_12,
        B_no_12,
        B_na_12,
        B_ok_13,
        B_no_13,
        B_na_13,
        B_ok_14,
        B_no_14,
        B_na_14,
        B_ok_15,
        B_no_15,
        B_na_15,
        B_ok_16,
        B_no_16,
        B_na_16,
        B_ok_17,
        B_no_17,
        B_na_17,
        B_ok_21, 
        B_no_21,
        B_na_21,
        B_ok_22, 
        B_no_22,
        B_na_22,
        B_ok_23, 
        B_no_23,
        B_na_23,
        B_ok_24, 
        B_no_24,
        B_na_24,
        B_ok_25,
        B_no_25,
        B_na_25,
        B_ok_26, 
        B_no_26,
        B_na_26,
        B_ok_27, 
        B_no_27,
        B_na_27 ,
        B_ok_31,
        B_no_31,
        B_na_31,
        B_ok_32,
        B_no_32,
        B_na_32,
        B_ok_33,
        B_no_33,
        B_na_33,
        B_ok_34,
        B_no_34,
        B_na_34,
        B_ok_35,
        B_no_35,
        B_na_35,
        B_ok_36,
        B_no_36,
        B_na_36,
        T_INSTRUMENTO1,
        T_INSTRUMENTO2,
        T_INSTRUMENTO3,
        T_INSTRUMENTO4,
        T_INSTRUMENTO5,
        T_INSTRUMENTO6,
        T_INSTRUMENTO7,
        T_INSTRUMENTO8,
      	T_REGISTRO1,
        T_REGISTRO2,
        T_REGISTRO3,
        T_REGISTRO4,
        T_REGISTRO5,
        T_REGISTRO6,
        T_REGISTRO7,
		    T_REGISTRO8,
        T_VALIDADE1,
        T_VALIDADE2,
        T_VALIDADE3,
        T_VALIDADE4,
        T_VALIDADE5,
        T_VALIDADE6,
        T_VALIDADE7,
        T_VALIDADE8) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 
        ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 
        ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )""", (T_PEP,T_NOMEPROJETO,B_ok_11,B_no_11,B_na_11,B_ok_12,B_no_12,B_na_12,B_ok_13,B_no_13,B_na_13,B_ok_14,B_no_14,B_na_14,B_ok_15,B_no_15,B_na_15,B_ok_16,B_no_16,B_na_16,B_ok_17,B_no_17,B_na_17,_ok_21, B_no_21,B_na_21,_ok_22, B_no_22,B_na_22,B_ok_23, B_no_23,B_na_23,B_ok_24, B_no_24,B_na_24,B_ok_25,B_no_25,B_na_25,B_ok_26, B_no_26,B_na_26,B_ok_27, B_no_27,B_na_27 ,B_ok_31,B_no_31,B_na_31,B_ok_32,B_no_32,B_na_32,B_ok_33,B_no_33,B_na_33,B_ok_34,B_no_34,B_na_34,B_ok_35,B_no_35,B_na_35,B_ok_36,B_no_36,B_na_36,T_INSTRUMENTO1,T_INSTRUMENTO2,T_INSTRUMENTO3,T_INSTRUMENTO4,T_INSTRUMENTO5,T_INSTRUMENTO6,T_INSTRUMENTO7,T_INSTRUMENTO8,T_REGISTRO1,T_REGISTRO2,T_REGISTRO3,T_REGISTRO4,T_REGISTRO5,T_REGISTRO6,T_REGISTRO7,T_REGISTRO8,T_VALIDADE1,T_VALIDADE2,T_VALIDADE3,T_VALIDADE4,T_VALIDADE5,T_VALIDADE6,T_VALIDADE7,T_VALIDADE8))
    dbase.commit()